# Generated by Django 2.2.4 on 2023-08-11 17:27

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, choices=[('NI', 'NewInstallation'), ('SEC', 'ServiceOnExistingConnection'), ('RC', 'RemoveConnection'), ('ENQ', 'Enquiry')], max_length=15, null=True, validators=[djchoices.choices.ChoicesValidator({'ENQ': 'Enquiry', 'NI': 'NewInstallation', 'RC': 'RemoveConnection', 'SEC': 'ServiceOnExistingConnection'})])),
                ('no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('stage', models.CharField(blank=True, choices=[('Cr', 'Created'), ('Pr', 'Progress'), ('Dn', 'Done')], max_length=15, null=True, validators=[djchoices.choices.ChoicesValidator({'Cr': 'Created', 'Dn': 'Done', 'Pr': 'Progress'})])),
            ],
        ),
    ]
