# Generated by Django 2.2.4 on 2023-08-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='requestor_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='requestor_name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
