# Generated by Django 2.2.4 on 2023-08-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20230812_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
